### ISSUE TITLE
Error when trying to start python text2image_cli.py

### ISSUE THREAD

**Issue by KintCark** [zehr0s/mobile-stable-diffusion#1]
I'm getting error when I try to run the start script:

(.venv) root@localhost:~/mobile-stable-diffusion# python text2image_cli.py                                            Traceback (most recent call last):                           File "/root/mobile-stable-diffusion/text2image_cli.py", line 29, in <module>                                            pipeline = DiffusionPipeline.from_pretrained(
  File "/root/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn            return fn(*args, **kwargs)
  File "/root/.venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 667, in from_pretrained
    raise ValueError(                                      ValueError: The provided pretrained_model_name_or_path "./Models/model.txt" is neither a valid local path nor a valid repo id. Please check the parameter.

Is there a fix for this?

**Comment by KintCark** [comment]
Nvm I fixed it the python thinks that model.txt files is a model so I removed it and now everything works 💪
